enum JobState {
  QUEUEING = "QUEUEING",
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  SUCCESS = "SUCCESS",
  TIMEOUT = "TIMEOUT",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  UNAPPROVED = "UNAPPROVED",
}

export default JobState;
