spring:
  cache:
    type: none
  application:
    name: hpc-interface
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:hpc_interface}?stringtype=unspecified
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant-path-matcher

logging:
  file:
    path: ${HPC_INTERFACE_LOG_PATH:log}
  # level:
  #   org.springframework.security: TRACE
  #   org.opensaml: DEBUG

# MUST use SSL for SAML
server:
  ssl:
    enabled: true
    certificate: classpath:certificates/cert.crt
    certificate-private-key: classpath:certificates/private.key
  port: 8443
