spring:
  cache:
    type: none
  application:
    name: hpc-interface
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yaml
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:hpc_interface}?stringtype=unspecified
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:
              entity-id: http://www.okta.com/exk6odvqkb5jgzPph5d7
              verification:
                credentials:
                  - certificate-location: "classpath:certificates/okta.crt"
              singlesignon:
                url: https://dev-00449127.okta.com/app/dev-00449127_springboottest_1/exk6odvqkb5jgzPph5d7/sso/saml
                sign-request: false

logging:
  file:
    path: ${HPC_INTERFACE_LOG_PATH:log}
  level:
    io.zonky.test.db.postgres: FATAL
    # org.springframework.security: TRACE
    # org.opensaml: DEBUG

# MUST use SSL for SAML
server:
  ssl:
    enabled: true
    certificate: classpath:certificates/cert.crt
    certificate-private-key: classpath:certificates/private.key
  port: 8443
