openapi: 3.0.3
info:
  title: HPC Interface API
  version: v1.0
servers:
  - url: https://hpc-interface-dev.ua.edu/
paths:
  /api/batches:
    $ref: paths/batches/root.yaml
  /api/batches/{batchId}:
    $ref: paths/batches/batchId/root.yaml
  /api/batches/{batchId}/approve:
    $ref: paths/batches/batchId/approve.yaml
  /api/batches/{batchId}/cancel:
    $ref: paths/batches/batchId/cancel.yaml
  /api/batches/{batchId}/jobs:
    $ref: paths/batches/batchId/jobs/root.yaml
  /api/batches/{batchId}/jobs/{jobId}:
    $ref: paths/batches/batchId/jobs/jobId/root.yaml
  /api/batches/{batchId}/jobs/{jobId}/cancel:
    $ref: paths/batches/batchId/jobs/jobId/cancel.yaml
  /api/scripts:
    $ref: paths/scripts/root.yaml
  /api/scripts/{scriptId}:
    $ref: paths/scripts/scriptId.yaml
  /api/users/me:
    $ref: paths/users/me/root.yaml
  /api/users/me/regenerate:
    $ref: paths/users/me/regenerate.yaml
  /api/users/me/check-ssh:
    $ref: paths/users/me/check-ssh.yaml
