name: eslint

on:
  push:
    paths:
      - "interface/**"
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd interface install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: --cwd interface eslint .
      - uses: borales/actions-yarn@v3.0.0
